### ISSUE TITLE
Cleanup in docs and classes before milestone

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#426]
There are few things that could be worked on before 2.9 work:
- [x] full benchmarks
- [ ] improve performance using benchmarks on pure python code
- [x] check docstrings (few could use fixing)
- [x] Const redesign
- [x] Lazy* build methods (denied)
- [x] add OSX to Travis (denied)
- [ ] add mkfs.ext2 sample generator
- [ ] import examples from Kaitai
